language: ruby

rvm:
  - "2.0.0"
  - "2.1.1"
  - "2.2.0"

gemfile:
  - "gemfiles/rails_40.gemfile"
  - "gemfiles/rails_42.gemfile"

before_install:
  - gem install bundler

script: "bundle exec rake spec"
